=begin
#Moonlogs

#Moonlogs API

OpenAPI spec version: 1.10.8
Contact: shalpack@gmail.com
Generated by: https://github.com/swagger-api/swagger-codegen.git
Swagger Codegen version: 3.0.52
=end

module MoonlogsRuby
  VERSION = '1.10.8'
end
