=begin
#Moonlogs

#Moonlogs API

OpenAPI spec version: 1.0.1
Contact: shalpack@gmail.com
Generated by: https://github.com/swagger-api/swagger-codegen.git
Swagger Codegen version: 3.0.52
=end

require 'date'

module MoonlogsRuby
  class UserRole
    MEMBER = 'Member'.freeze
    ADMIN = 'Admin'.freeze
    SYSTEM = 'System'.freeze

    # Builds the enum from string
    # @param [String] The enum value in the form of the string
    # @return [String] The enum value
    def build_from_hash(value)
      constantValues = UserRole.constants.select { |c| UserRole::const_get(c) == value }
      raise "Invalid ENUM value #{value} for class #UserRole" if constantValues.empty?
      value
    end
  end
end
