=begin
#Moonlogs

#Moonlogs API

OpenAPI spec version: 1.14.0
Contact: shalpack@gmail.com
Generated by: https://github.com/swagger-api/swagger-codegen.git
Swagger Codegen version: 3.0.52
=end

# Common files
require 'moonlogs-ruby/api_client'
require 'moonlogs-ruby/api_error'
require 'moonlogs-ruby/version'
require 'moonlogs-ruby/configuration'

# Models
require 'moonlogs-ruby/models/action_request'
require 'moonlogs-ruby/models/action_response'
require 'moonlogs-ruby/models/api_token_request'
require 'moonlogs-ruby/models/api_token_response'
require 'moonlogs-ruby/models/condition'
require 'moonlogs-ruby/models/credentials'
require 'moonlogs-ruby/models/inline_response_200'
require 'moonlogs-ruby/models/inline_response_200_1'
require 'moonlogs-ruby/models/inline_response_200_10'
require 'moonlogs-ruby/models/inline_response_200_11'
require 'moonlogs-ruby/models/inline_response_200_12'
require 'moonlogs-ruby/models/inline_response_200_13'
require 'moonlogs-ruby/models/inline_response_200_14'
require 'moonlogs-ruby/models/inline_response_200_15'
require 'moonlogs-ruby/models/inline_response_200_16'
require 'moonlogs-ruby/models/inline_response_200_17'
require 'moonlogs-ruby/models/inline_response_200_18'
require 'moonlogs-ruby/models/inline_response_200_19'
require 'moonlogs-ruby/models/inline_response_200_2'
require 'moonlogs-ruby/models/inline_response_200_3'
require 'moonlogs-ruby/models/inline_response_200_4'
require 'moonlogs-ruby/models/inline_response_200_5'
require 'moonlogs-ruby/models/inline_response_200_6'
require 'moonlogs-ruby/models/inline_response_200_7'
require 'moonlogs-ruby/models/inline_response_200_8'
require 'moonlogs-ruby/models/inline_response_200_9'
require 'moonlogs-ruby/models/level'
require 'moonlogs-ruby/models/meta'
require 'moonlogs-ruby/models/one_of_record_request_level'
require 'moonlogs-ruby/models/one_of_record_response_level'
require 'moonlogs-ruby/models/one_of_user_request_role'
require 'moonlogs-ruby/models/one_of_user_response_role'
require 'moonlogs-ruby/models/record_request'
require 'moonlogs-ruby/models/record_response'
require 'moonlogs-ruby/models/role'
require 'moonlogs-ruby/models/schema_field'
require 'moonlogs-ruby/models/schema_kind'
require 'moonlogs-ruby/models/schema_request'
require 'moonlogs-ruby/models/schema_response'
require 'moonlogs-ruby/models/session'
require 'moonlogs-ruby/models/tag_request'
require 'moonlogs-ruby/models/tag_response'
require 'moonlogs-ruby/models/user_request'
require 'moonlogs-ruby/models/user_response'

# APIs
require 'moonlogs-ruby/api/default_api'

module MoonlogsRuby
  class << self
    # Customize default settings for the SDK using block.
    #   MoonlogsRuby.configure do |config|
    #     config.username = "xxx"
    #     config.password = "xxx"
    #   end
    # If no block given, return the default Configuration object.
    def configure
      if block_given?
        yield(Configuration.default)
      else
        Configuration.default
      end
    end
  end
end
