=begin
#Moonlogs

#Moonlogs API

OpenAPI spec version: 1.0
Contact: shalpack@gmail.com
Generated by: https://github.com/swagger-api/swagger-codegen.git
Swagger Codegen version: 3.0.52
=end

require 'spec_helper'
require 'json'
require 'date'

# Unit tests for MoonlogsRuby::UserRole
# Automatically generated by swagger-codegen (github.com/swagger-api/swagger-codegen)
# Please update as you see appropriate
describe 'UserRole' do
  before do
    # run before each test
    @instance = MoonlogsRuby::UserRole.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of UserRole' do
    it 'should create an instance of UserRole' do
      expect(@instance).to be_instance_of(MoonlogsRuby::UserRole)
    end
  end
end
