# -*- encoding: utf-8 -*-

=begin
#Moonlogs

#Moonlogs API

OpenAPI spec version: 1.18.0
Contact: shalpack@gmail.com
Generated by: https://github.com/swagger-api/swagger-codegen.git
Swagger Codegen version: 3.0.52
=end

$:.push File.expand_path("../lib", __FILE__)
require "moonlogs-ruby/version"

Gem::Specification.new do |s|
  s.name        = "moonlogs-ruby"
  s.version     = MoonlogsRuby::VERSION
  s.platform    = Gem::Platform::RUBY
  s.authors     = ["Swagger-Codegen"]
  s.email       = ["shalpack@gmail.com"]
  s.homepage    = "https://github.com/swagger-api/swagger-codegen"
  s.summary     = "Moonlogs Ruby Gem"
  s.description = "Moonlogs API"
  s.license     = "Unlicense"
  s.required_ruby_version = ">= 1.9"

  s.add_runtime_dependency 'typhoeus', '~> 1.0', '>= 1.0.1'
  s.add_runtime_dependency 'json', '~> 2.1', '>= 2.1.0'

  s.add_development_dependency 'rspec', '~> 3.6', '>= 3.6.0'

  s.files         = `find *`.split("\n").uniq.sort.select { |f| !f.empty? }
  s.test_files    = `find spec/*`.split("\n")
  s.executables   = []
  s.require_paths = ["lib"]
end
