=begin
#Moonlogs

#Moonlogs API

OpenAPI spec version: 0.3.5
Contact: shalpack@gmail.com
Generated by: https://github.com/swagger-api/swagger-codegen.git
Swagger Codegen version: 3.0.52
=end

require 'spec_helper'
require 'json'
require 'date'

# Unit tests for MoonlogsRuby::OneOfUserRole
# Automatically generated by swagger-codegen (github.com/swagger-api/swagger-codegen)
# Please update as you see appropriate
describe 'OneOfUserRole' do
  before do
    # run before each test
    @instance = MoonlogsRuby::OneOfUserRole.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of OneOfUserRole' do
    it 'should create an instance of OneOfUserRole' do
      expect(@instance).to be_instance_of(MoonlogsRuby::OneOfUserRole)
    end
  end
end
