=begin
#Moonlogs

#Moonlogs API

OpenAPI spec version: 0.3.0
Contact: shalpack@gmail.com
Generated by: https://github.com/swagger-api/swagger-codegen.git
Swagger Codegen version: 3.0.52
=end

require 'spec_helper'
require 'json'
require 'date'

# Unit tests for MoonlogsRuby::SchemaSearch
# Automatically generated by swagger-codegen (github.com/swagger-api/swagger-codegen)
# Please update as you see appropriate
describe 'SchemaSearch' do
  before do
    # run before each test
    @instance = MoonlogsRuby::SchemaSearch.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of SchemaSearch' do
    it 'should create an instance of SchemaSearch' do
      expect(@instance).to be_instance_of(MoonlogsRuby::SchemaSearch)
    end
  end
  describe 'test attribute "title"' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  describe 'test attribute "description"' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

end
