name: Generate and Publish Ruby Client

on:
  repository_dispatch:
    types: [generate-publish-client]

jobs:
  generate-and-publish-client:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Download Swagger YAML
        run: |
          curl -sSLo swagger.yaml https://raw.githubusercontent.com/pijng/moonlogs/master/internal/api/swagger.yaml

      - name: Download Swagger Codegen
        run: |
         wget https://repo1.maven.org/maven2/io/swagger/codegen/v3/swagger-codegen-cli/3.0.27/swagger-codegen-cli-3.0.27.jar -O swagger-codegen-cli.jar

      - name: Install Java
        uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: '11'

      - name: Generate Ruby Client
        run: |
          java -jar swagger-codegen-cli.jar generate -i swagger.yaml -l ruby -o moonlogs-ruby --additional-properties gemName=moonlogs-ruby gemVersion=${{ github.event.client_payload.tag_version }}

      - name: Add Generated Files to Git
        run: |
          git add moonlogs-ruby

      - name: Commit Changes
        run: |
          git commit -m "Update client to v${{ github.event.client_payload.tag_version }}" -a

      - name: Push Changes
        run: |
          git push origin HEAD:${{ github.ref }}

      - name: Build Gem
        run: |
          gem build moonlogs-ruby/moonlogs-ruby.gemspec

      - name: Publish Gem to RubyGems
        run: |
          gem push moonlogs-ruby-*.gem